### PR TITLE
One way to display Latex in markdown

### PR DESCRIPTION
**Pull request by aviks**
Though I'm not entirely sure this is a good idea. 

To see how it looks like: https://github.com/aviks/SmoothingKernels.jl

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Yeah, I'm not totally sold on this since it makes the Markdown a bit inscrutable and still doesn't render correctly: the absolute value bars get inverted.

**Comment by aviks** [comment]
Indeed. Nevermind.

**Comment by johnmyleswhite** [comment]
Thanks for the effort!

**Comment by aviks** [comment]
No worries, its was just a 5 minutes of cut/paste :)

**Pull request closed without merging**
